font=JetBrainsMono Nerd Font:size=12

[colors-dark]
background=161616
foreground=f2f4f8

## Normal colors
regular0=282828  # black
regular1=ee5396  # red
regular2=25be6a  # green
regular3=08bdba  # yellow
regular4=78a9ff  # blue
regular5=be95ff  # magenta
regular6=33b1ff  # cyan
regular7=dfdfe0  # white

## Bright colors
bright0=484848   # bright black
bright1=f16da6   # bright red
bright2=46c880   # bright green
bright3=2dc7c4   # bright yellow
bright4=8cb6ff   # bright blue
bright5=c8a5ff   # bright magenta
bright6=52bdff   # bright cyan
bright7=e4e4e5   # bright white

## Dim colors
dim0=222222      # dim black
dim1=ca4780      # dim red
dim2=1fa25a      # dim green
dim3=07a19e      # dim yellow
dim4=6690d9      # dim blue
dim5=a27fd9      # dim magenta
dim6=2b96d9      # dim cyan
dim7=bebebe      # dim white

## Misc colors
selection-foreground=f2f4f8
selection-background=2a2a2a
urls=33b1ff

